export const FETCH_LISTS = 'lists/FETCH_LISTS'
export const SET_LISTS = 'lists/SET_LISTS'
export const FETCH_LIST = 'lists/FETCH_LIST'
export const SET_LIST = 'lists/SET_LIST'
export const CREATE_LIST = 'lists/CREATE_LIST'
export const DELETE_LIST = 'lists/DELETE_LIST'
export const ADD_TO_LIST = 'lists/ADD_TO_LIST'
export const REMOVE_FROM_LIST = 'lists/REMOVE_FROM_LIST'
