export const FETCH_TRENDING = 'dashboard/FETCH_TRENDING'
export const SET_TRENDING = 'dashboard/SET_TRENDING'
export const FETCH_SEARCH = 'dashboard/REQUEST_SEARCH'
export const SET_SEARCH = 'dashboard/SET_SEARCH'
export const CLEAR_SEARCH = 'dashboard/CLEAR_SEARCH'
